name = "video-queue-consumer"
main = "src/video-queue-consumer.ts"
compatibility_date = "2024-01-01"

# R2 Buckets
[[r2_buckets]]
binding = "VIDEOS_BUCKET"
bucket_name = "oa-videos"

[[r2_buckets]]
binding = "HIGHLIGHTS_BUCKET"
bucket_name = "oa-highlights"

# KV Namespaces
[[kv_namespaces]]
binding = "KV_IDEMP"
id = "5948d4a91ac04b50904a06c923221994"  # Reuse existing for both metadata and idempotency

# Queue Consumer
[[queues.consumers]]
queue = "highlights-queue"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "highlights-dlq"

# Environment variables
[vars]
ENVIRONMENT = "production"
