// Using native fetch in Node 18+

const API = 'http://127.0.0.1:8787';

async function run() {
    try {
        // 1. Get Admin Token
        console.log('1. Getting Admin Token...');
        const tokenRes = await fetch(`${API}/dev/admin-jwt`, { method: 'POST' });
        const tokenData = await tokenRes.json();
        if (!tokenData.success) throw new Error('Failed to get token');
        const token = tokenData.token;
        console.log('   Token received.');

        // 2. Create Product
        console.log('2. Creating Test Product...');
        const prodRes = await fetch(`${API}/api/v1/shop/products`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${token}`
            },
            body: JSON.stringify({
                title: 'E2E Test Product',
                description: 'Generated by E2E test',
                vendor: 'test',
                variants: [{ title: 'Standard', price_gbp: 1500 }]
            })
        });
        const prodData = await prodRes.json();
        // Support both fresh creation (success:true) or just verifying list if fails? 
        // Creating should work.
        let variantId;
        if (prodData.success) {
            console.log('   Product created:', prodData.product.id);
            variantId = prodData.product.variants[0].id;
        } else {
            console.log('   Create failed, trying to list...', prodData);
            // Fallback: list
            const listRes = await fetch(`${API}/api/v1/shop/products`);
            const listData = await listRes.json();
            if (listData.data && listData.data.length > 0) {
                variantId = listData.data[0].variants[0].id;
                console.log('   Using existing variant:', variantId);
            } else {
                throw new Error('No products available to test');
            }
        }

        // 3. Create Cart
        console.log('3. Creating Cart...');
        const cartRes = await fetch(`${API}/api/v1/shop/cart`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ tenantId: 'test_tenant' })
        });
        const cartData = await cartRes.json();
        if (!cartData.success) throw new Error('Cart creation failed');
        const cartId = cartData.cart.id;
        console.log('   Cart created:', cartId);

        // 4. Add to Cart
        console.log('4. Adding Item to Cart...');
        const addRes = await fetch(`${API}/api/v1/shop/cart/${cartId}/items`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ variantId, quantity: 2 })
        });
        const addData = await addRes.json();
        if (!addData.success) throw new Error('Add to cart failed: ' + addData.error);
        console.log('   Item added. Cart total:', addData.cart.items[0].priceGbp * addData.cart.items[0].quantity);

        // 5. Checkout
        console.log('5. Creating Checkout Session...');
        const checkRes = await fetch(`${API}/api/v1/shop/checkout`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ cartId, customerEmail: 'e2e@example.com' })
        });
        // This might fail if STRIPE_SECRET_KEY is not set.
        const checkData = await checkRes.json();
        if (checkData.success) {
            console.log('   Checkout Session Created!');
            console.log('   URL:', checkData.url);
        } else {
            console.warn('   Checkout failed (expected if no secrets):', checkData.error);
        }

        console.log('E2E Test Completed Successfully (Stripe success dependent on secrets).');

    } catch (e) {
        console.error('E2E Test Failed:', e);
        process.exit(1);
    }
}

run();
