name: CI
on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    working-directory: backend
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint || echo "no lint script"

      - name: Typecheck
        run: npm run typecheck || echo "no typecheck script"

      - name: Unit tests
        run: npm test -- --run || echo "no tests"

      - name: Build
        run: npm run build
      - run: npm ci --workspaces
      - run: npm run -ws lint || echo "no lint script"
      - run: npm run -ws typecheck || echo "no typecheck script"
      - run: npm test --workspaces -- --run || echo "no tests"
      - run: npm run -ws build
