name: Deploy Web to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - 'web/**'
      - 'packages/sdk/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            web/package-lock.json
            packages/sdk/package-lock.json

      - name: Install SDK dependencies
        working-directory: ./packages/sdk
        run: npm ci

      - name: Build SDK
        working-directory: ./packages/sdk
        run: npm run build

      - name: Install web dependencies
        working-directory: ./web
        run: npm ci

      - name: Build web app
        working-directory: ./web
        run: npm run build
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_DEFAULT_TENANT: ${{ secrets.NEXT_PUBLIC_DEFAULT_TENANT || 'demo' }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: team-platform-web
          directory: web/.next
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
